export class OrderList {
    orderId:number= 1; // autoGenerated
    paymentId:string = ""; // Payment
    userId:string = "";
    userName:string = "";
    mobileNumber:string = "";
    prescriptionImage:any;
    accepted:boolean = false;
    totalAmount!:number;
}
