import { flatten } from "@angular/compiler";

export class OrderList {
    orderId:number= 1; // autoGenerated
    paymentId:string = ""; // Payment
    userId:string = "";
    userName:string = "";
    mobileNumber:string = "";
    prescriptionImage:any;
    status:number = -1;  
    totalAmount!:number;
}

/* 
status keys 

-1 : inti 
0 : ordered
1 : accepted 
2 : rejected
*/